### ISSUE TITLE
Observaciones - Tabla de simbolos

### ISSUE THREAD

**Issue by matiasllunasanchez** [matiasllunasanchez/lyc_compiler#3]
En ts.txt faltan columnas NOMBRE TIPO VALOR LONGITUD y no se autogenera siempre que se utilice un factor que sea del tipo REAL, probar con un programa que contenga a := 99999.99 a := 99. a := .9999 habiendo borrado previamente el archivo de la tabla de símbolos

**Comment by matiasllunasanchez** [comment]
Ya se agregaron las columnas de la tabla de simbolos, falta revisar lo del factor del tiporeal.

**Comment by AMondaini** [comment]
![image](https://user-images.githubusercontent.com/21976674/169710802-faa437d1-130b-496f-91fd-e19a0840e24e.png)

![image](https://user-images.githubusercontent.com/21976674/169710790-4b1756b1-b162-4890-9ff4-30ab975b055c.png)

**Comment by AMondaini** [comment]
![image](https://user-images.githubusercontent.com/21976674/170315767-76b4ea76-2f56-44a2-9871-04f06258259e.png)

**Comment by matiasllunasanchez** [comment]
Teoricamente ya anda
